server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5333/anime
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
management:
  endpoint:
    caches:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      jmx:
        enabled: true

word-config:
  luckyWord: Potato
  preamble: Today luckyWord is